import { Header, Notification } from "@/components";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const Provider = dynamic(() => import("@/components/provider"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  // TODO: get this value from Jonas's implementation
  const isOnlyPassKey = true;
  return (
    <html lang="en" className="bg-black">
      <body
        className={cn(
          inter.className,
          "flex min-h-screen flex-col bg-gradient-to-br from-black to-slate-900",
        )}
      >
        <Provider>
          <Header />
          {isOnlyPassKey && (
            <Notification
              description="CAUTION: Your account is currently only secured by your device passkey. Please add a <b>mobile key</b> to enable recovery on other devices."
              type="warning"
            />
          )}
          <main id="main" className="relative flex w-full grow">
            {children}
          </main>
          <div id="modal-root" />
        </Provider>
      </body>
    </html>
  );
}
