import { Header, PasskeyNotification } from "@/components";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const Provider = dynamic(() => import("@/components/provider"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="bg-black">
      <body
        className={cn(
          inter.className,
          "flex min-h-screen flex-col bg-gradient-to-br from-black to-slate-900",
        )}
      >
        <Provider>
          <Header />
          <PasskeyNotification />
          <main id="main" className="relative flex w-full grow">
            {children}
          </main>
          <div id="modal-root" />
        </Provider>
      </body>
    </html>
  );
}
