import "./globals.css";
import { Header } from "@/components";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className="bg-black">
      <body
        className={cn(
          inter.className,
          "flex min-h-screen flex-col bg-gradient-to-br from-black to-slate-900",
        )}
      >
        <Header />
        <main id="main" className="relative flex w-full grow">
          {children}
        </main>
      </body>
    </html>
  );
}
