import { Navbar } from "@/components";
import { SignAndBroadcastTransactionUserInteractionHandler } from "@/user-interactions/sign-and-broadcast-transaction-handler";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}): JSX.Element {
  return (
    <section className="relative flex w-full ">
      <Navbar />
      {
        // 96px for bottom-navbar and 80px for header
      }
      <div className="flex grow overflow-auto max-sm:h-[calc(100vh-96px-80px)]">
        <SignAndBroadcastTransactionUserInteractionHandler>
          {children}
        </SignAndBroadcastTransactionUserInteractionHandler>
      </div>
    </section>
  );
}
