export enum Phase {
  KEYGEN = "keygen",
  SIGN = "sign",
}

// Configuration parameters retrieved from the server
// during the handshake.
export interface Parameters {
  parties: number;
  threshold: number;
}

// Private key share for GG2020.
export interface KeyShare {
  localKey: LocalKey;
  publicKey: number[];
  address: string;
}

// Opaque type for the private key share.
export interface LocalKey {
  // Index of the key share.
  i: number;
  // Threshold for key share signing.
  t: number;
  // Total number of parties.
  n: number;
}

// Generated by the server to signal this party wants
// to be included in key generation.
//
// The uuid is injected from the session that owns
// this party signup.
export interface PartySignup {
  number: number;
  uuid: string;
}

export interface Session {
  uuid: string;
  partySignup?: PartySignup;
}

// State for party signup round during keygen.
export interface PartySignupInfo {
  parameters: Parameters;
  partySignup: PartySignup;
}

export interface SessionInfo {
  groupId: string;
  sessionId: string;
  parameters: Parameters;
  partySignup: PartySignup;
}

export interface SignResult {
  r: string;
  s: string;
  recid: number;
}

export interface SignMessage {
  signature: SignResult;
  public_key: number[];
  address: string;
}

export interface EthUserOp {
  sender: string;
  nonce: string;
  initCode: string;
  callData: string;
  callGasLimit: string;
  verificationGasLimit: string;
  preVerificationGas: string;
  maxFeePerGas: string;
  maxPriorityFeePerGas: string;
  paymasterAndData: string;
}

export interface RustEthUserOp {
  sender: string;
  nonce: string;
  init_code: number[];
  call_data: number[];
  call_gas_limit: string;
  verification_gas_limit: string;
  pre_verification_gas: string;
  max_fee_per_gas: string;
  max_priority_fee_per_gas: string;
  paymaster_and_data: number[];
  signature: number[];
}

export interface SignatureRecid {
  r: string;
  s: string;
  recid: number;
}

export interface ExistingKeyRefreshItem {
  Existing: {
    // This should be fine
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    key: any;
    updated_party_index?: number;
  };
}

export interface NewKeyRefreshItem {
  New: {
    party_index: number;
  };
}

export type KeyRefreshItem = ExistingKeyRefreshItem | NewKeyRefreshItem;

export interface RustEthUserOp {
  sender: string;
  nonce: string;
  init_code: number[];
  call_data: number[];
  call_gas_limit: string;
  verification_gas_limit: string;
  pre_verification_gas: string;
  max_fee_per_gas: string;
  max_priority_fee_per_gas: string;
  paymaster_and_data: number[];
  signature: number[];
}

export interface EcValueType {
  curve: string;
  scalar: string;
}

export interface ShareType {
  k_i: EcValueType;
  pubkey: EcValueType;
  R: EcValueType;
  sigma_i: EcValueType;
}
