name: GitHub Packages
on:
  push:
    branches:
      - feature/modal
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: ferluisxd/create-npmrc@3
        with:
          org_name: obi-wallet
        env:
          AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: yarn
      - run: yarn publish-libs
