name: JavaScript
on:
  - push
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: sudo apt-get update
      - run: yarn setup
      - run: yarn checks
